const express = require('express');
const { pool } = require('../db');
const { auth } = require('../middleware/auth');
const router = express.Router();

router.get('/',async(_,res)=>{try{const[rows]=await pool.execute(`SELECT c.id,c.user_id,c.brand,c.model,c.year,c.price,c.km,c.city,c.body_type,c.fuel,c.transmission,c.description,c.plan,c.status,c.created_at,(SELECT ci.image FROM car_images ci WHERE ci.car_id=c.id ORDER BY ci.id ASC LIMIT 1) AS image,u.name AS seller_name,u.phone AS seller_phone FROM cars c LEFT JOIN users u ON u.id=c.user_id WHERE c.status='approved' ORDER BY CASE WHEN c.plan='VIP' THEN 1 WHEN c.plan='مميز' THEN 2 ELSE 3 END,c.id DESC`);res.json(rows);}catch(e){console.error(e);res.status(500).json({message:'تعذر تحميل السيارات'});}});
router.get('/mine/list',auth,async(req,res)=>{try{const[rows]=await pool.execute(`SELECT c.id,c.brand,c.model,c.year,c.price,c.km,c.city,c.body_type,c.fuel,c.transmission,c.description,c.plan,c.status,c.created_at,(SELECT ci.image FROM car_images ci WHERE ci.car_id=c.id ORDER BY ci.id ASC LIMIT 1) AS image FROM cars c WHERE c.user_id=? ORDER BY c.id DESC`,[req.user.id]);res.json(rows);}catch(e){console.error(e);res.status(500).json({message:'تعذر تحميل إعلاناتك'});}});
router.get('/:id',async(req,res)=>{try{const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({message:'رقم السيارة غير صحيح'});const[cars]=await pool.execute(`SELECT c.id,c.user_id,c.brand,c.model,c.year,c.price,c.km,c.city,c.body_type,c.fuel,c.transmission,c.description,c.plan,c.status,c.created_at,u.name AS seller_name,u.phone AS seller_phone FROM cars c LEFT JOIN users u ON u.id=c.user_id WHERE c.id=? AND c.status='approved' LIMIT 1`,[id]);if(!cars.length)return res.status(404).json({message:'السيارة غير موجودة'});const[images]=await pool.execute(`SELECT id,image FROM car_images WHERE car_id=? ORDER BY id ASC`,[id]);res.json({...cars[0],images});}catch(e){console.error(e);res.status(500).json({message:'تعذر تحميل السيارة'});}});
router.post('/',auth,async(req,res)=>{const connection=await pool.getConnection();try{const{brand,model,year,price,km,city,fuel,transmission,description,plan,phone,body_type}=req.body;let imageUrls=[];if(Array.isArray(req.body.images))imageUrls=req.body.images.map(String).filter(Boolean);else if(typeof req.body.images==='string'&&req.body.images.trim()){try{const parsed=JSON.parse(req.body.images);if(Array.isArray(parsed))imageUrls=parsed.map(String).filter(Boolean);}catch(_) {}}if(!brand||!model||!year||!price||!city||!body_type)return res.status(400).json({message:'أكمل بيانات السيارة'});if(imageUrls.length===0)return res.status(400).json({message:'أضف صور السيارة'});if(imageUrls.length>8)return res.status(400).json({message:'الحد الأقصى 8 صور'});const[users]=await connection.execute(`SELECT phone FROM users WHERE id=? LIMIT 1`,[req.user.id]);const finalPhone=String(phone||users[0]?.phone||'').trim();if(!finalPhone)return res.status(400).json({message:'أضف رقم هاتف للحساب أولاً'});const selectedPlan=['عادي','مميز','VIP'].includes(plan)?plan:'عادي';await connection.beginTransaction();await connection.execute(`UPDATE users SET phone=? WHERE id=?`,[finalPhone,req.user.id]);const[result]=await connection.execute(`INSERT INTO cars (user_id,brand,model,year,price,km,city,body_type,category,fuel,transmission,description,plan,status) VALUES (?,?,?,?,?,?,?,? ,NULL,?,?,?,?, 'pending')`,[req.user.id,String(brand).trim(),String(model).trim(),Number(year),Number(price),Number(km||0),String(city).trim(),String(body_type).trim(),fuel||'بنزين',transmission||'أوتوماتيك',description||'',selectedPlan]);for(const image of imageUrls)await connection.execute(`INSERT INTO car_images(car_id,image) VALUES(?,?)`,[result.insertId,image]);await connection.commit();res.status(201).json({message:'تم إرسال السيارة للمراجعة',id:result.insertId,status:'pending',plan:selectedPlan,images:imageUrls});}catch(e){try{await connection.rollback();}catch(_){}console.error('CREATE CAR ERROR:',e);res.status(500).json({message:'تعذر إنشاء إعلان السيارة'});}finally{connection.release();}});
router.delete('/:id',auth,async(req,res)=>{try{const[result]=await pool.execute(`DELETE FROM cars WHERE id=? AND user_id=?`,[Number(req.params.id),req.user.id]);if(!result.affectedRows)return res.status(404).json({message:'الإعلان غير موجود'});res.json({message:'تم حذف الإعلان'});}catch(e){console.error(e);res.status(500).json({message:'تعذر حذف الإعلان'});}});
module.exports=router;
