import 'package:flutter/material.dart';
import '../services/api_service.dart';
import 'admin_payment_screen.dart';
import 'admin_requests_screen.dart';
import 'admin_cars_screen.dart';
import 'admin_management_screen.dart';

class AdminScreen extends StatefulWidget{const AdminScreen({super.key,required this.api});final ApiService api;@override State<AdminScreen> createState()=>_AdminScreenState();}
class _AdminScreenState extends State<AdminScreen>{bool loading=true,owner=false;int cars=0,users=0,requests=0;@override void initState(){super.initState();load();}
Future<void> load()async{setState(()=>loading=true);try{final d=await widget.api.getAdminData();final me=await widget.api.me();if(!mounted)return;final u=me is Map&&me['user'] is Map?me['user']:{};setState((){owner=u['role']=='owner';cars=_i(d,'cars_count');users=_i(d,'users_count');requests=_i(d,'requests_count');});}on ApiException catch(e){msg(e.message);}finally{if(mounted)setState(()=>loading=false);}}
int _i(dynamic d,String k)=>d is Map&&d[k]!=null?int.tryParse(d[k].toString())??0:0;void msg(String s){if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}void open(Widget page)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>page));
Widget card(IconData icon,String title,String sub,VoidCallback tap)=>Container(margin:const EdgeInsets.only(bottom:10),decoration:BoxDecoration(color:const Color(0xFF15151B),borderRadius:BorderRadius.circular(17),border:Border.all(color:const Color(0xFF292932))),child:ListTile(onTap:tap,leading:Container(width:45,height:45,decoration:BoxDecoration(color:const Color(0xFF28141F),borderRadius:BorderRadius.circular(13)),child:Icon(icon,color:const Color(0xFFFF176F))),title:Text(title,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),subtitle:Text(sub,style:const TextStyle(color:Colors.white38,fontSize:11)),trailing:const Icon(Icons.chevron_left_rounded,color:Colors.white30)));
Widget stat(IconData icon,String title,int value)=>Expanded(child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFF15151B),borderRadius:BorderRadius.circular(17),border:Border.all(color:const Color(0xFF292932))),child:Column(children:[Icon(icon,color:const Color(0xFFFF176F),size:25),const SizedBox(height:7),Text('$value',style:const TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900)),Text(title,style:const TextStyle(color:Colors.white54,fontSize:10))])));
@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:const Color(0xFF08080B),appBar:AppBar(title:const Text('لوحة الإدارة',style:TextStyle(fontWeight:FontWeight.w900)),centerTitle:true,actions:[IconButton(onPressed:loading?null:load,icon:const Icon(Icons.refresh_rounded))]),body:loading?const Center(child:CircularProgressIndicator(color:Color(0xFFFF176F))):RefreshIndicator(color:const Color(0xFFFF176F),onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF321222),Color(0xFF15151B)]),borderRadius:BorderRadius.circular(21)),child:const Text('إدارة ZYOCAR',style:TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900))),const SizedBox(height:18),Row(children:[stat(Icons.directions_car_rounded,'السيارات',cars),const SizedBox(width:8),stat(Icons.people_rounded,'المستخدمون',users),const SizedBox(width:8),stat(Icons.pending_actions_rounded,'الطلبات',requests)]),const SizedBox(height:25),const Text('الإدارة',style:TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:12),card(Icons.payments_rounded,'طريقة الاستلام والتحويل','بيانات الاستلام من السيرفر',()=>open(AdminPaymentScreen(api:widget.api))),card(Icons.fact_check_rounded,'طلبات الموافقة','الإعلانات والمعارض وطلبات التسجيل',()=>open(AdminRequestsScreen(api:widget.api))),card(Icons.directions_car_rounded,'إدارة السيارات','كل السيارات وحالاتها من السيرفر',()=>open(AdminCarsScreen(api:widget.api))),card(Icons.people_rounded,'المستخدمون','حسابات المستخدمين من السيرفر',()=>msg('قائمة المستخدمين مربوطة بالسيرفر')),if(owner)card(Icons.admin_panel_settings_rounded,'تحديد الأدمن','المالك فقط: تعيين أو إلغاء الأدمن',()=>open(AdminManagementScreen(api:widget.api))),Container(margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFF15151B),borderRadius:BorderRadius.circular(16)),child:Text(owner?'أنت المالك: يمكنك تحديد الأدمن من هنا.':'أنت أدمن: صلاحيات الأدمن تُدار من المالك.',style:const TextStyle(color:Colors.white54,fontSize:12,height:1.5))) ])));
}
