import 'package:flutter/material.dart';
import '../models/car.dart' hide ApiService, ApiException;
import '../services/api_service.dart';
import '../widgets/car_brand_logo.dart';

class CarsScreen extends StatefulWidget{const CarsScreen({super.key,required this.api});final ApiService api;@override State<CarsScreen> createState()=>_CarsScreenState();}
class _CarsScreenState extends State<CarsScreen>{bool loading=true;String? error;List<Car> cars=[];String brand='الكل';final brands=['الكل','تويوتا','لكزس','نيسان','هيونداي','كيا','هوندا','بي إم دبليو','مرسيدس','أودي','فورد'];
@override void initState(){super.initState();_loadCars();}Future<void> _loadCars()async{if(mounted)setState(()=>loading=true);try{final d=await widget.api.getCars();if(!mounted)return;setState(()=>cars=d.whereType<Map>().map((e)=>Car.fromJson(Map<String,dynamic>.from(e))).toList());}catch(e){if(mounted)setState(()=>error=e is ApiException?e.message:'تعذر تحميل السيارات');}finally{if(mounted)setState(()=>loading=false);}}
String _price(int v)=>'\$${v.toString().replaceAllMapped(RegExp(r'(\d)(?=(\d{3})+(?!\d))'),(m)=>'${m[1]},')}';
void _filter(){showModalBottomSheet(context:context,backgroundColor:const Color(0xFF11151F),shape:const RoundedRectangleBorder(borderRadius:BorderRadius.vertical(top:Radius.circular(24))),builder:(_)=>Directionality(textDirection:TextDirection.rtl,child:SafeArea(child:Padding(padding:const EdgeInsets.all(18),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('فلترة السيارات',style:TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:14),...brands.map((b)=>ListTile(onTap:(){setState(()=>brand=b);Navigator.pop(context);},leading:Icon(b==brand?Icons.radio_button_checked:Icons.radio_button_off,color:b==brand?const Color(0xFFFF176F):Colors.white38),title:Text(b,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold))))]))));}
Widget _image(Car c)=>c.image!=null&&c.image!.isNotEmpty?Image.network(widget.api.imageUrl(c.image!),fit:BoxFit.cover,errorBuilder:(_,__,___)=>_fallback(c)):_fallback(c);Widget _fallback(Car c)=>Container(color:const Color(0xFF0C1421),alignment:Alignment.center,child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[CarBrandLogo(brand:c.brand,size:70),const SizedBox(height:6),Text(c.brand,style:const TextStyle(color:Colors.white70))]));
Widget _card(Car c)=>Container(margin:const EdgeInsets.only(bottom:14),clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:const Color(0xFF15151B),borderRadius:BorderRadius.circular(20),border:Border.all(color:c.isVip?const Color(0xFFFF176F):Colors.white12)),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[SizedBox(height:205,child:Stack(fit:StackFit.expand,children:[_image(c),Positioned(top:10,right:10,child:CarBrandLogo(brand:c.brand,size:48,background:Colors.black54)),if(c.isVip)Positioned(top:10,left:10,child:Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:const Color(0xFFFF176F),borderRadius:BorderRadius.circular(20)),child:const Text('VIP',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900)))),Positioned(bottom:10,left:10,child:Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:Colors.black87,borderRadius:BorderRadius.circular(20)),child:Text(_price(c.price),style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900))))])),Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('${c.brand} ${c.model}',style:const TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('${c.year} • ${c.city} • ${c.km} كم',style:const TextStyle(color:Colors.white54,fontSize:12))]))]));
@override Widget build(BuildContext context){final shown=brand=='الكل'?cars:cars.where((c)=>c.brand==brand).toList();return Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:const Color(0xFF07090F),appBar:AppBar(backgroundColor:const Color(0xFF07090F),title:const Text('السيارات',style:TextStyle(fontWeight:FontWeight.w900)),actions:[IconButton(onPressed:_filter,tooltip:'فلترة',icon:const Icon(Icons.tune_rounded,color:Color(0xFFFF176F)))]),body:loading?const Center(child:CircularProgressIndicator(color:Color(0xFFFF176F))):error!=null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!,style:const TextStyle(color:Colors.white70)),TextButton(onPressed:_loadCars,child:const Text('إعادة المحاولة'))])):RefreshIndicator(color:const Color(0xFFFF176F),onRefresh:_loadCars,child:ListView(padding:const EdgeInsets.all(16),children:[if(brand!='الكل')Padding(padding:const EdgeInsets.only(bottom:12),child:Chip(label:Text('فلتر: $brand'),deleteIcon:const Icon(Icons.close_rounded),onDeleted:()=>setState(()=>brand='الكل'))),if(shown.isEmpty)const Padding(padding:EdgeInsets.only(top:100),child:Center(child:Text('ماكو سيارات منشورة حالياً',style:TextStyle(color:Colors.white54)))) else ...shown.map(_card)])));}}
