import 'package:flutter/material.dart';
import '../services/api_service.dart';

const _pink=Color(0xFFFF176F),_blue=Color(0xFF1597FF),_bg=Color(0xFF060810),_surface=Color(0xFF0E1522);

class ShowroomsScreen extends StatefulWidget{const ShowroomsScreen({super.key,required this.api});final ApiService api;@override State<ShowroomsScreen> createState()=>_ShowroomsScreenState();}
class _ShowroomsScreenState extends State<ShowroomsScreen>{bool loading=true;String? error;List<Map<String,dynamic>> items=[];@override void initState(){super.initState();_load();}
Future<void>_load()async{setState((){loading=true;error=null;});try{final data=await widget.api.getShowrooms();final raw=data is List?data:data is Map&&data['showrooms'] is List?data['showrooms']:const[];if(!mounted)return;setState((){items=raw.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();loading=false;});}catch(e){if(mounted)setState((){loading=false;error=e is ApiException?e.message:'تعذر تحميل المعارض';});}}
Future<void>_subscribe()async{if(!widget.api.isLoggedIn){_msg('سجّل الدخول أولاً');return;}final name=TextEditingController(),phone=TextEditingController(),city=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(backgroundColor:_surface,title:const Text('اشتراك معرض',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),content:Column(mainAxisSize:MainAxisSize.min,children:[const Text('100,000 د.ع شهرياً',style:TextStyle(color:_pink,fontWeight:FontWeight.w900,fontSize:18)),const SizedBox(height:12),_field(name,'اسم المعرض'),_field(phone,'رقم الهاتف',keyboard:TextInputType.phone),_field(city,'المحافظة')]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('متابعة'))]));if(ok!=true)return;try{await widget.api.requestShowroom(name:name.text,phone:phone.text,city:city.text);if(mounted)_msg('تم إرسال طلب اشتراك المعرض للإدارة');}catch(e){if(mounted)_msg(e is ApiException?e.message:'تعذر إرسال الطلب');}finally{name.dispose();phone.dispose();city.dispose();}}
Widget _field(TextEditingController c,String hint,{TextInputType? keyboard})=>Padding(padding:const EdgeInsets.only(bottom:8),child:TextField(controller:c,keyboardType:keyboard,style:const TextStyle(color:Colors.white),decoration:InputDecoration(hintText:hint,hintStyle:const TextStyle(color:Colors.white38),filled:true,fillColor:Colors.black26,border:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(12))))));void _msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s),behavior:SnackBarBehavior.floating));
@override Widget build(BuildContext context){Widget body;if(loading)body=const Center(child:CircularProgressIndicator(color:_pink));else if(error!=null)body=Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!,style:const TextStyle(color:Colors.white70)),TextButton(onPressed:_load,child:const Text('إعادة المحاولة'))]));else body=ListView(padding:const EdgeInsets.all(15),children:[Container(margin:const EdgeInsets.only(bottom:14),padding:const EdgeInsets.all(16),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF2B1026),Color(0xFF101B2C)]),borderRadius:BorderRadius.circular(22),border:Border.all(color:_pink.withOpacity(.35))),child:Row(children:[const Icon(Icons.storefront_rounded,color:_pink,size:38),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('اشتراك أصحاب المعارض',style:TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('100,000 د.ع شهرياً',style:TextStyle(color:_pink,fontWeight:FontWeight.w900))])),FilledButton(onPressed:_subscribe,child:const Text('اشترك'))]),const SizedBox(height:2),if(items.isEmpty)const Padding(padding:EdgeInsets.only(top:70),child:Center(child:Text('لا توجد معارض معتمدة حالياً',style:TextStyle(color:Colors.white54)))) else ...items.map(_card)];return Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:_bg,appBar:AppBar(title:const Text('المعارض',style:TextStyle(fontWeight:FontWeight.w900)),backgroundColor:_bg),body:RefreshIndicator(color:_pink,onRefresh:_load,child:body)));}
Widget _card(Map<String,dynamic> x){final id=int.tryParse('${x['id']}')??0;return Container(margin:const EdgeInsets.only(bottom:12),decoration:BoxDecoration(color:_surface,borderRadius:BorderRadius.circular(20),border:Border.all(color:_blue.withOpacity(.22))),child:ListTile(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ShowroomDetailsScreen(api:widget.api,id:id))),leading:const Icon(Icons.storefront_rounded,color:_pink,size:34),title:Text('${x['name']??'معرض'}',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),subtitle:Text('📍 ${x['city']??''}\n☎ ${x['phone']??''}',style:const TextStyle(color:Colors.white54,height:1.5)),trailing:const Icon(Icons.chevron_left_rounded,color:Colors.white38)));}}

class ShowroomDetailsScreen extends StatefulWidget{const ShowroomDetailsScreen({super.key,required this.api,required this.id});final ApiService api;final int id;@override State<ShowroomDetailsScreen> createState()=>_ShowroomDetailsScreenState();}
class _ShowroomDetailsScreenState extends State<ShowroomDetailsScreen>{Map<String,dynamic>? showroom;List<Map<String,dynamic>> cars=[];bool loading=true;String? error;@override void initState(){super.initState();_load();}Future<void>_load()async{try{final d=await widget.api.getShowroom(widget.id);if(!mounted)return;final m=d is Map?Map<String,dynamic>.from(d):{};final raw=m['cars'];setState((){showroom=m['showroom'] is Map?Map<String,dynamic>.from(m['showroom']):null;cars=raw is List?raw.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList():[];loading=false;});}catch(e){if(mounted)setState((){loading=false;error=e is ApiException?e.message:'تعذر تحميل بيانات المعرض';});}}
@override Widget build(BuildContext context){if(loading)return const Scaffold(backgroundColor:_bg,body:Center(child:CircularProgressIndicator(color:_pink)));if(error!=null)return Scaffold(backgroundColor:_bg,appBar:AppBar(backgroundColor:_bg,title:const Text('صفحة المعرض')),body:Center(child:Text(error!,style:const TextStyle(color:Colors.white54))));final name=showroom?['name']?.toString()??'معرض',city=showroom?['city']?.toString()??'',phone=showroom?['phone']?.toString()??'';return Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:_bg,appBar:AppBar(title:const Text('صفحة المعرض',style:TextStyle(fontWeight:FontWeight.w900)),backgroundColor:_bg),body:ListView(padding:const EdgeInsets.all(15),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:_surface,borderRadius:BorderRadius.circular(24),border:Border.all(color:_pink.withOpacity(.4))),child:Column(children:[const Icon(Icons.storefront_rounded,color:_pink,size:48),const SizedBox(height:9),Text(name,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),Text('📍 $city',style:const TextStyle(color:Colors.white60)),Text('☎ $phone',style:const TextStyle(color:Colors.white60)),const SizedBox(height:12),const Text('الاشتراك الشهري: 100,000 د.ع',style:TextStyle(color:_pink,fontWeight:FontWeight.w900))])),const SizedBox(height:20),Text('سيارات المعرض (${cars.length})',style:const TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:10),...cars.map((car)=>Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:_surface,borderRadius:BorderRadius.circular(18)),child:Row(children:[const Icon(Icons.directions_car_rounded,color:_blue,size:42),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${car['brand']??''} ${car['model']??''}',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),Text('${car['year']??''} • ${car['city']??''}',style:const TextStyle(color:Colors.white54,fontSize:11)),Text('\$${car['price']??0}',style:const TextStyle(color:_pink,fontWeight:FontWeight.w900,fontSize:16))]))])))])));}}
